#define AND		0	
#define AS		1
#define BY		2
#define CHAR		3
#define CREATE		4
#define DISTINCT	5
#define DELETE		6
#define EXISTS		7
#define FROM		8
#define GROUP		9
#define HAVING		10
#define INSERT		11
#define INT		12
#define INTO		13
#define KEY		14
#define NOT		15
#define NULLX		16
#define OR		17
#define ORDER		18
#define PRIMARY		19
#define SELECT		20
#define SHOW		21
#define TABLE		22
#define TABLES		23
#define UNIQUE		24
#define UPDATE		25
#define VALUES		26
#define WHERE		27

#define COMPARISON	28
#define COMMA		29
#define PERIOD		30
#define COLON		31
#define SEMICOLON	32
#define OPENBRACE	33
#define CLOSEBRACE	34
#define STAR		35
#define IDENTIFIER	36
#define INTNUM		37
#define QUOTE		38
